set -g default-terminal "screen-256color"

# keybindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

unbind C-b
set-option -g prefix `
bind-key ` send-prefix

bind r source-file ~/.tmux.conf

bind | split-window -h
bind - split-window -v

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind l select-pane -R
bind h select-pane -L

bind -n M-F11 set -qg status-bg colour25
bind -n M-F12 set -qg status-bg colour40
bind -n S-up \
	send-keys M-F12 \; \
	set -qg status-bg colour25 \; \
	unbind -n M-Left \; \
	unbind -n M-Right \; \
	unbind -n M-Up \; \
	unbind -n M-Down \; \
	set -qg prefix C-b
bind -n S-down \
	send-keys M-F11 \; \
	set -qg status-bg colour40 \; \
  bind -n M-Left select-pane -L \; \
  bind -n M-Right select-pane -R \; \
  bind -n M-Up select-pane -U \; \
  bind -n M-Down select-pane -D \; \
	set -qg prefix `

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# NOTE: keep at the bottom of the file 
# init tmux plugin manager
run -b '~/.tmux/plugins/tpm/tpm'
